// ./app/(site)/programs-data.ts

export interface VisaCountry {
  name: string;
  note?: "*" | "**"; // * = Visa on arrival, ** = Electronic Travel Authorization
}

export interface InvestmentOption {
  type: "contribution" | "real-estate" | "bonds" | "other";
  title: string;
  description: string;
  startingPrice: string;
  currency: string;
}

export interface ProgramData {
  slug: string;
  country: string;
  type: "citizenship" | "residency";
  tagline: string;
  heroImage: string;
  highlights: string[];
  description: string;
  benefits: string[];
  investmentOptions: InvestmentOption[];
  visaFreeCountries: VisaCountry[];
}

export const programsData: Record<string, ProgramData> = {
  "st-lucia": {
    slug: "st-lucia",
    country: "St. Lucia",
    type: "citizenship",
    tagline: "Expand your global reach with a top-tier Caribbean passport",
    heroImage: "/images/st-lucia.webp",
    highlights: [
      "Citizenship for life",
      "Cost efficient investment options",
      "Visa-free access to more than 140 countries including the UK and Schengen Zone",
      "Member of the British Commonwealth",
      "Approval in 3+ months",
      "Up to 6 months of visa-free stay in UK",
    ],
    description: `St. Lucia Citizenship by Investment Program enables foreign investors to become citizens of St. Lucia in exchange for an economic contribution to the country. It has been one of the most popular and affordable Caribbean CBI programs among applicants.`,
    benefits: [
      "Part of the UN, the British Commonwealth, OECS, OAS, and CARICOM",
      "Citizenship is transferable to generations",
      "Fast Growing Economy",
      "Stable Democracy",
      "Straightforward process",
      "Ease of global and travel mobility",
      "Ability to live, work and study",
      "Citizenship for you, your spouse, children under 30 years of age, unmarried siblings, parents and grandparents including spouse's",
      "Dual/Multiple Citizenship",
      "Crypto-Friendly",
      "Vibrant touristic destination",
      "Business Friendly",
      "Favourable Tax Regime",
      "No education requirement",
      "High tolerancy and welcoming environment",
      "High quality of life",
      "High level of island safety",
      "Lower living cost",
      "Ideal country for families",
      "English as an official language",
      "No language test",
      "No physical residence requirement",
      "No wealth tax",
    ],
    investmentOptions: [
      {
        type: "contribution",
        title: "Contribution",
        description:
          "Non-refundable donation to the National Economy Fund starting from",
        startingPrice: "240,000",
        currency: "$",
      },
      {
        type: "real-estate",
        title: "Real Estate",
        description: "Investment in government-approved property starting from",
        startingPrice: "300,000",
        currency: "$",
      },
      {
        type: "bonds",
        title: "Government Bonds",
        description: "Investment in government bonds starting from",
        startingPrice: "300,000",
        currency: "$",
      },
    ],
    visaFreeCountries: [
      { name: "Andorra" },
      { name: "Anguilla" },
      { name: "Antigua and Barbuda" },
      { name: "Argentina" },
      { name: "Armenia", note: "*" },
      { name: "Aruba" },
      { name: "Austria" },
      { name: "Bahamas" },
      { name: "Bangladesh", note: "*" },
      { name: "Barbados" },
      { name: "Belgium" },
      { name: "Belize" },
      { name: "Bermuda" },
      { name: "Bolivia", note: "*" },
      { name: "Bonaire; St. Eustatius and Saba" },
      { name: "Bosnia and Herzegovina" },
      { name: "Botswana" },
      { name: "British Virgin Islands" },
      { name: "Bulgaria" },
      { name: "Burundi", note: "*" },
      { name: "Cambodia", note: "*" },
      { name: "Cape Verde Islands", note: "*" },
      { name: "Cayman Islands" },
      { name: "Chile" },
      { name: "Colombia" },
      { name: "Comoro Islands", note: "*" },
      { name: "Cook Islands" },
      { name: "Costa Rica" },
      { name: "Croatia" },
      { name: "Cuba" },
      { name: "Curacao" },
      { name: "Cyprus" },
      { name: "Czech Republic" },
      { name: "Denmark" },
      { name: "Dominica" },
      { name: "Dominican Republic" },
      { name: "Ecuador" },
      { name: "Egypt", note: "*" },
      { name: "El Salvador" },
      { name: "Estonia" },
      { name: "eSwatini" },
      { name: "Faroe Islands" },
      { name: "Fiji" },
      { name: "Finland" },
      { name: "France" },
      { name: "French Guiana" },
      { name: "French Polynesia" },
      { name: "French West Indies" },
      { name: "Germany" },
      { name: "Gibraltar" },
      { name: "Greece" },
      { name: "Greenland" },
      { name: "Grenada" },
      { name: "Guatemala" },
      { name: "Guinea-Bissau", note: "*" },
      { name: "Guyana" },
      { name: "Haiti" },
      { name: "Honduras" },
      { name: "Hong Kong (SAR China)" },
      { name: "Hungary" },
      { name: "Iceland" },
      { name: "Iran", note: "*" },
      { name: "Ireland" },
      { name: "Israel" },
      { name: "Italy" },
      { name: "Jamaica" },
      { name: "Jordan", note: "*" },
      { name: "Kenya" },
      { name: "Kiribati" },
      { name: "Kosovo" },
      { name: "Laos", note: "*" },
      { name: "Latvia" },
      { name: "Lesotho" },
      { name: "Liechtenstein" },
      { name: "Lithuania" },
      { name: "Luxembourg" },
      { name: "Macao (SAR China)", note: "*" },
      { name: "Madagascar", note: "*" },
      { name: "Malawi" },
      { name: "Malaysia" },
      { name: "Maldives", note: "*" },
      { name: "Malta" },
      { name: "Mauritania", note: "*" },
      { name: "Mauritius" },
      { name: "Mayotte" },
      { name: "Micronesia" },
      { name: "Moldova" },
      { name: "Monaco" },
      { name: "Montenegro" },
      { name: "Montserrat" },
      { name: "Mozambique", note: "*" },
      { name: "Nepal", note: "*" },
      { name: "Netherlands" },
      { name: "New Caledonia" },
      { name: "Nicaragua" },
      { name: "Niue" },
      { name: "North Macedonia" },
      { name: "Norway" },
      { name: "Pakistan", note: "**" },
      { name: "Palau Islands", note: "*" },
      { name: "Palestinian Territory" },
      { name: "Panama" },
      { name: "Peru" },
      { name: "Philippines" },
      { name: "Poland" },
      { name: "Portugal" },
      { name: "Reunion" },
      { name: "Romania" },
      { name: "Rwanda", note: "*" },
      { name: "Samoa", note: "*" },
      { name: "San Marino" },
      { name: "Senegal" },
      { name: "Seychelles", note: "*" },
      { name: "Sierra Leone", note: "*" },
      { name: "Singapore" },
      { name: "Slovakia" },
      { name: "Slovenia" },
      { name: "Solomon Islands", note: "*" },
      { name: "Somalia", note: "*" },
      { name: "South Korea", note: "**" },
      { name: "Spain" },
      { name: "Sri Lanka", note: "**" },
      { name: "St. Helena", note: "*" },
      { name: "St. Kitts and Nevis" },
      { name: "St. Maarten" },
      { name: "St. Vincent and the Grenadines" },
      { name: "Suriname" },
      { name: "Sweden" },
      { name: "Switzerland" },
      { name: "Taiwan (Chinese Taipei)" },
      { name: "Tanzania" },
      { name: "The Gambia" },
      { name: "Timor-Leste", note: "*" },
      { name: "Togo", note: "*" },
      { name: "Tonga", note: "*" },
      { name: "Trinidad and Tobago" },
      { name: "Tunisia" },
      { name: "Turks and Caicos Islands" },
      { name: "Tuvalu", note: "*" },
      { name: "Uganda", note: "*" },
      { name: "United Kingdom" },
      { name: "Uzbekistan" },
      { name: "Vanuatu" },
      { name: "Vatican City" },
      { name: "Venezuela" },
      { name: "Zambia" },
      { name: "Zimbabwe" },
    ],
  },

  turkey: {
    slug: "turkey",
    country: "Turkey",
    type: "citizenship",
    tagline: "Increase your wealth in a safe haven between Europe and Asia",
    heroImage: "/images/turkey.webp",
    highlights: [
      "Citizenship for life",
      "Crucial business location between Asia and Europe",
      "Access to the Black, Mediterranean, Aegean and Marmara Seas",
      "A great deal of investment options",
      "Visa-free access to more than 115 countries, including Singapore, South Korea and Japan",
      "USA E-2 Treaty Country",
      "Approval in 8+ months",
    ],
    description: `Turkey Citizenship by Investment Program enables foreign investors to become Turkish citizens through a wide range of investment options. The program also allows dual citizenship and provides a potential pathway to E-2 Investor Visa for the U.S. Ideal for investors seeking mobility, business expansion, or a backup plan.`,
    benefits: [
      "Citizenship is transferable to generations",
      "Fast Growing Strong Economy",
      "Ability to live, work and study anywhere in Turkey",
      "Citizenship for you, your spouse, and children under 18 years of age",
      "High return on investment",
      "Crypto-Friendly Real Estate Options",
      "Vast, Dynamic and Profitable Real Estate Market",
      "Highly educated and skilled labor force",
      "Vibrant touristic destination",
      "Enhanced business access to advanced economies thanks to its strategic location and transportation links",
      "Tax discounts for your business",
      "Multicultural and welcoming environment",
      "No source of funds requirement",
      "No education requirement",
      "No age restriction",
      "Business Friendly",
      "Part of the UN, NATO, OSCE, WTO and OECD",
      "Free access to quality education and healthcare",
      "Dual/Multiple Citizenship",
      "Warm Mediterranean climate",
      "Rich and diverse culture",
      "Access to advanced economies with free trade agreements",
      "Young and active population with half under the age of 31",
      "Lower living cost",
      "Ideal country for families",
      "No interview",
      "No language test",
      "No physical residence requirement",
      "Thriving expat community",
    ],
    investmentOptions: [
      {
        type: "real-estate",
        title: "Real Estate",
        description: "Investment in property starting from",
        startingPrice: "400,000",
        currency: "$",
      },
      {
        type: "bonds",
        title: "Government Bonds",
        description: "Investment in government bonds starting from",
        startingPrice: "500,000",
        currency: "$",
      },
      {
        type: "other",
        title: "Starting a Business",
        description: "Create jobs for at least 50 people",
        startingPrice: "50",
        currency: "jobs",
      },
      {
        type: "other",
        title: "Fixed Capital",
        description: "Investment in fixed capital starting from",
        startingPrice: "500,000",
        currency: "$",
      },
      {
        type: "other",
        title: "Private Pension System",
        description: "Investment in private pension system starting from",
        startingPrice: "500,000",
        currency: "$",
      },
    ],
    visaFreeCountries: [
      { name: "Albania" },
      { name: "Antigua and Barbuda" },
      { name: "Argentina" },
      { name: "Armenia", note: "*" },
      { name: "Azerbaijan" },
      { name: "Bahamas" },
      { name: "Bahrain", note: "*" },
      { name: "Bangladesh", note: "*" },
      { name: "Barbados" },
      { name: "Belarus" },
      { name: "Belize" },
      { name: "Bolivia" },
      { name: "Bosnia and Herzegovina" },
      { name: "Botswana" },
      { name: "Brazil" },
      { name: "British Virgin Islands" },
      { name: "Brunei" },
      { name: "Burundi", note: "*" },
      { name: "Cambodia", note: "*" },
      { name: "Cape Verde Islands", note: "*" },
      { name: "Chile" },
      { name: "Colombia" },
      { name: "Comoro Islands", note: "*" },
      { name: "Cook Islands" },
      { name: "Costa Rica" },
      { name: "Dominica" },
      { name: "Dominican Republic" },
      { name: "Ecuador" },
      { name: "El Salvador" },
      { name: "eSwatini" },
      { name: "Fiji" },
      { name: "Gabon", note: "*" },
      { name: "Georgia" },
      { name: "Guatemala" },
      { name: "Guinea-Bissau", note: "*" },
      { name: "Haiti" },
      { name: "Honduras" },
      { name: "Hong Kong (SAR China)" },
      { name: "Indonesia", note: "*" },
      { name: "Iran" },
      { name: "Jamaica" },
      { name: "Japan" },
      { name: "Jordan" },
      { name: "Kazakhstan" },
      { name: "Kosovo" },
      { name: "Kuwait", note: "*" },
      { name: "Kyrgyzstan" },
      { name: "Laos", note: "*" },
      { name: "Lebanon", note: "*" },
      { name: "Macao (SAR China)" },
      { name: "Madagascar", note: "*" },
      { name: "Malaysia" },
      { name: "Maldives", note: "*" },
      { name: "Marshall Islands", note: "*" },
      { name: "Mauritania", note: "*" },
      { name: "Mauritius" },
      { name: "Mexico", note: "**" },
      { name: "Micronesia" },
      { name: "Moldova" },
      { name: "Mongolia" },
      { name: "Montenegro" },
      { name: "Morocco" },
      { name: "Mozambique", note: "*" },
      { name: "Namibia", note: "*" },
      { name: "Nepal", note: "*" },
      { name: "Nicaragua" },
      { name: "Niue" },
      { name: "North Macedonia" },
      { name: "Oman" },
      { name: "Pakistan", note: "**" },
      { name: "Palau Islands", note: "*" },
      { name: "Panama" },
      { name: "Paraguay" },
      { name: "Peru" },
      { name: "Philippines" },
      { name: "Qatar" },
      { name: "Rwanda", note: "*" },
      { name: "Samoa", note: "*" },
      { name: "Sao Tome and Principe" },
      { name: "Senegal" },
      { name: "Serbia" },
      { name: "Seychelles", note: "*" },
      { name: "Sierra Leone", note: "*" },
      { name: "Singapore" },
      { name: "Somalia", note: "*" },
      { name: "South Africa" },
      { name: "South Korea", note: "**" },
      { name: "Sri Lanka", note: "**" },
      { name: "St. Kitts and Nevis" },
      { name: "St. Lucia" },
      { name: "St. Vincent and the Grenadines" },
      { name: "Sudan", note: "*" },
      { name: "Taiwan (Chinese Taipei)", note: "*" },
      { name: "Tajikistan", note: "*" },
      { name: "Tanzania", note: "*" },
      { name: "Thailand" },
      { name: "The Gambia" },
      { name: "Timor-Leste", note: "*" },
      { name: "Togo", note: "*" },
      { name: "Tonga", note: "*" },
      { name: "Trinidad and Tobago" },
      { name: "Tunisia" },
      { name: "Tuvalu", note: "*" },
      { name: "Uganda", note: "*" },
      { name: "Ukraine" },
      { name: "Uruguay" },
      { name: "Uzbekistan" },
      { name: "Vanuatu" },
      { name: "Venezuela" },
      { name: "Zambia", note: "*" },
      { name: "Zimbabwe", note: "*" },
    ],
  },

  vanuatu: {
    slug: "vanuatu",
    country: "Vanuatu",
    type: "citizenship",
    tagline:
      "Citizenship with soul, in the South Pacific. Welcome to your Pacific haven with Vanuatu citizenship.",
    heroImage: "/images/vanuatu.webp",
    highlights: [
      "Citizenship for life",
      "Family Friendly",
      "Visa free access to more than 90 countries including Russia, Hong Kong, Singapore and Australia",
      "Tax Heaven",
      "Approval in 2+ months",
    ],
    description: `Vanuatu's Citizenship by Investment program offers an efficient route to second citizenship through a qualifying donation starting from $140,000. With no residency or language requirements, and one of the fastest processing times, this program provides lifetime citizenship in a peaceful South Pacific island nation. Enjoy visa-free access to over 90 countries, favorable tax benefits, and the serenity of tropical island living for you and your family.`,
    benefits: [
      "Part of the UN, World Trade Organization, IMF, NAM and ADB",
      "Citizenship is transferable to next generations",
      "Visa free access to more than 90 countries including Russia, Hong Kong, Singapore and Australia",
      "Straightforward and fast process",
      "High approval rates",
      "Multiple investment options",
      "Ability to live, work and study",
      "Citizenship for you, your spouse, children under 25 years of age and parents over 50 years of age",
      "Dual/Multiple Citizenship",
      "Vibrant touristic destination",
      "Business Friendly",
      "Tax Heaven",
      "No education requirement",
      "No management experience",
      "No source of funds requirements",
      "No residency requirements",
      "No language test",
      "Family Friendly",
      "Opportunity to apply UK Universities",
      "Bislama, English and French as the official languages",
      "Safe, low-crime country with a welcoming local culture",
    ],
    investmentOptions: [
      {
        type: "contribution",
        title: "Government Contribution",
        description:
          "Non-refundable government contribution to Vanuatu Development Support Program (DSP) starting from",
        startingPrice: "140,400",
        currency: "$",
      },
      {
        type: "other",
        title: "Fund Investment",
        description:
          "Conditionally recoverable investment to CNO Future Fund (Coconut Oil Foundation), starting from $165,000. Fixed contribution amount for a family of up to 4 people. Up to $50,000 of the contribution can be returned in 5 years",
        startingPrice: "165,000",
        currency: "$",
      },
    ],
    visaFreeCountries: [
      { name: "Antigua and Barbuda" },
      { name: "Bahamas" },
      { name: "Barbados" },
      { name: "Belarus" },
      { name: "Belize", note: "*" },
      { name: "Botswana" },
      { name: "Costa Rica", note: "*" },
      { name: "Dominica" },
      { name: "Dominican Republic", note: "*" },
      { name: "Ecuador" },
      { name: "Fiji", note: "*" },
      { name: "Guatemala", note: "*" },
      { name: "Honduras" },
      { name: "Israel" },
      { name: "Jamaica" },
      { name: "Kiribati" },
      { name: "Lebanon", note: "*" },
      { name: "Marshall Islands", note: "*" },
      { name: "Papua New Guinea", note: "*" },
      { name: "Saint Kitts and Nevis" },
      { name: "Saint Vincent and the Grenadines" },
      { name: "Samoa" },
      { name: "Seychelles" },
      { name: "Singapore" },
      { name: "Solomon Islands", note: "*" },
      { name: "South Africa" },
      { name: "Sri Lanka", note: "**" },
      { name: "Suriname", note: "*" },
      { name: "Tanzania", note: "*" },
      { name: "Thailand" },
      { name: "Tonga", note: "*" },
      { name: "Trinidad and Tobago" },
      { name: "Turks and Caicos Islands" },
      { name: "Tuvalu" },
      { name: "United Kingdom", note: "**" },
      { name: "Vanuatu" },
    ],
  },

  "antigua-barbuda": {
    slug: "antigua-barbuda",
    country: "Antigua & Barbuda",
    type: "citizenship",
    tagline: "Enjoy the 365 marvelous island beaches for 365 days.",
    heroImage: "/images/antigua-barbuda.webp",
    highlights: [
      "Citizenship for life",
      "Most cost efficient CBI for large families",
      "Visa free access to more than 140 countries including UK, EU, Singapore, and Hong Kong",
      "Member of the British Commonwealth",
      "Approval in 6+ months",
      "Enjoy the 365 marvelous island beaches for 365 days",
    ],
    description: `Antigua & Barbuda Citizenship by Investment Program enables foreign investors to become citizens of Antigua & Barbuda in exchange for an economic contribution to the country. It has been one of the most powerful and popular Caribbean CBI programs over the years among high-net-worth individuals.`,
    benefits: [
      "Visa free access to more than 140 countries including UK, EU, Singapore, and Hong Kong",
      "Part of the UN, the British Commonwealth, OSCE, OAS, and CARICOM",
      "Citizenship for you, your spouse, children under 30 years of age, parents, grandparents, and unmarried siblings including spouse's",
      "Citizenship is transferable to generations",
      "Fully Remote Procedure",
      "Fast Growing Economy",
      "Straightforward process",
      "Ease of global and travel mobility",
      "Ability to live, work and study",
      "High return on investment",
      "Vibrant touristic destination",
      "Crypto-Friendly",
      "Business Friendly",
      "Dual/Multiple Citizenship",
      "High quality of life",
      "Lower living cost",
      "Most cost efficient CBI for large families",
      "English as an official language",
      "No physical residence required for application",
      "No wealth tax",
      "No education requirement",
    ],
    investmentOptions: [
      {
        type: "contribution",
        title: "NDF Contribution",
        description:
          "Non-refundable contribution to the Antigua and Barbuda National Development Fund (NDF) for a family of up to 5 starting from",
        startingPrice: "230,000",
        currency: "$",
      },
      {
        type: "contribution",
        title: "UWI Donation",
        description:
          "Donation to the University of West Indies Five Islands Campus Fund (UWI) for the family of 6 starting from",
        startingPrice: "260,000",
        currency: "$",
      },
      {
        type: "real-estate",
        title: "Real Estate",
        description: "Investment in government-approved property starting from",
        startingPrice: "300,000",
        currency: "$",
      },
    ],
    visaFreeCountries: [
      { name: "Albania" },
      { name: "Andorra" },
      { name: "Anguilla" },
      { name: "Armenia", note: "*" },
      { name: "Aruba" },
      { name: "Austria" },
      { name: "Bahamas" },
      { name: "Bangladesh", note: "*" },
      { name: "Barbados" },
      { name: "Belarus" },
      { name: "Belgium" },
      { name: "Belize" },
      { name: "Bermuda" },
      { name: "Bolivia", note: "*" },
      { name: "Bonaire; St. Eustatius and Saba" },
      { name: "Bosnia and Herzegovina" },
      { name: "Botswana" },
      { name: "Brazil" },
      { name: "British Virgin Islands" },
      { name: "Bulgaria" },
      { name: "Burundi", note: "*" },
      { name: "Cambodia", note: "*" },
      { name: "Cape Verde Islands", note: "*" },
      { name: "Cayman Islands" },
      { name: "Chile" },
      { name: "Colombia" },
      { name: "Comoro Islands", note: "*" },
      { name: "Cook Islands" },
      { name: "Costa Rica" },
      { name: "Croatia" },
      { name: "Cuba" },
      { name: "Curacao" },
      { name: "Cyprus" },
      { name: "Czech Republic" },
      { name: "Denmark" },
      { name: "Dominica" },
      { name: "Dominican Republic" },
      { name: "Ecuador" },
      { name: "Egypt", note: "*" },
      { name: "El Salvador" },
      { name: "Estonia" },
      { name: "eSwatini" },
      { name: "Faroe Islands" },
      { name: "Fiji" },
      { name: "Finland" },
      { name: "France" },
      { name: "French Guiana" },
      { name: "French Polynesia" },
      { name: "French West Indies" },
      { name: "Georgia" },
      { name: "Germany" },
      { name: "Gibraltar" },
      { name: "Greece" },
      { name: "Greenland" },
      { name: "Grenada" },
      { name: "Guatemala" },
      { name: "Guinea-Bissau", note: "*" },
      { name: "Guyana" },
      { name: "Haiti" },
      { name: "Honduras" },
      { name: "Hong Kong (SAR China)" },
      { name: "Hungary" },
      { name: "Iceland" },
      { name: "Iran", note: "*" },
      { name: "Ireland" },
      { name: "Italy" },
      { name: "Jamaica" },
      { name: "Jordan", note: "*" },
      { name: "Kiribati" },
      { name: "Kosovo" },
      { name: "Laos", note: "*" },
      { name: "Latvia" },
      { name: "Lebanon", note: "*" },
      { name: "Lesotho" },
      { name: "Liechtenstein" },
      { name: "Lithuania" },
      { name: "Luxembourg" },
      { name: "Macao (SAR China)", note: "*" },
      { name: "Madagascar", note: "*" },
      { name: "Malawi" },
      { name: "Malaysia" },
      { name: "Maldives", note: "*" },
      { name: "Malta" },
      { name: "Mauritania", note: "*" },
      { name: "Mauritius" },
      { name: "Mayotte" },
      { name: "Micronesia" },
      { name: "Moldova" },
      { name: "Monaco" },
      { name: "Montenegro" },
      { name: "Montserrat" },
      { name: "Mozambique", note: "*" },
      { name: "Nepal", note: "*" },
      { name: "Netherlands" },
      { name: "New Caledonia" },
      { name: "Nicaragua" },
      { name: "Niue" },
      { name: "North Macedonia" },
      { name: "Norway" },
      { name: "Palau Islands", note: "*" },
      { name: "Panama" },
      { name: "Peru" },
      { name: "Philippines" },
      { name: "Poland" },
      { name: "Portugal" },
      { name: "Qatar" },
      { name: "Reunion" },
      { name: "Romania" },
      { name: "Russian Federation" },
      { name: "Rwanda", note: "*" },
      { name: "Samoa", note: "*" },
      { name: "San Marino" },
      { name: "Senegal", note: "*" },
      { name: "Serbia" },
      { name: "Seychelles", note: "*" },
      { name: "Sierra Leone", note: "*" },
      { name: "Singapore" },
      { name: "Slovakia" },
      { name: "Slovenia" },
      { name: "Solomon Islands", note: "*" },
      { name: "Somalia", note: "*" },
      { name: "South Africa" },
      { name: "South Korea", note: "**" },
      { name: "Spain" },
      { name: "Sri Lanka", note: "**" },
      { name: "St. Helena", note: "*" },
      { name: "St. Kitts and Nevis" },
      { name: "St. Lucia" },
      { name: "St. Maarten" },
      { name: "St. Vincent and the Grenadines" },
      { name: "Suriname" },
      { name: "Sweden" },
      { name: "Switzerland" },
      { name: "Tanzania" },
      { name: "The Gambia" },
      { name: "Timor-Leste", note: "*" },
      { name: "Togo", note: "*" },
      { name: "Trinidad and Tobago" },
      { name: "Tunisia" },
      { name: "Turks and Caicos Islands" },
      { name: "Tuvalu", note: "*" },
      { name: "Uganda" },
      { name: "Ukraine" },
      { name: "United Kingdom" },
      { name: "Uzbekistan" },
      { name: "Vanuatu" },
      { name: "Vatican City" },
      { name: "Venezuela" },
      { name: "Zambia" },
      { name: "Zimbabwe" },
    ],
  },

  dominica: {
    slug: "dominica",
    country: "Dominica",
    type: "citizenship",
    tagline: "Boost your wealth with the Nature Isle of the Caribbean",
    heroImage: "/images/dominica.webp",
    highlights: [
      "Citizenship for life",
      "Cost efficient investment options",
      "Visa-free access to more than 130 countries including EU, Singapore, Hong Kong, China and Russia",
      "Member of the British Commonwealth",
      "No physical residence required",
      "Approval in 3+ months",
    ],
    description: `Dominica Citizenship by Investment Program enables foreign investors to become Dominican citizens in exchange for an economic contribution to the country. It is the second longest-running citizenship program in the world and has helped shape Caribbean CBI standards.`,
    benefits: [
      "Visa-free access to more than 130 countries including EU, Singapore, Hong Kong, China and Russia",
      "Part of the UN, the British Commonwealth, OECS, OAS, and CARICOM",
      "Citizenship is transferable to generations",
      "Fully Remote Procedure",
      "Fast Growing Economy",
      "Stable Democracy",
      "Straightforward process",
      "Ease of global and travel mobility",
      "Ability to live, work and study",
      "Dual/Multiple Citizenship",
      "Citizenship for you, your spouse, children under 30 years of age, parents and grandparents including spouse's",
      "Crypto-Friendly",
      "Vibrant touristic destination",
      "Business Friendly",
      "High quality of life",
      "High level of island safety",
      "Lower living cost",
      "Ideal country for families",
      "English as an official language",
      "No language test",
      "No physical residence requirement",
      "No wealth tax",
      "No education requirement",
    ],
    investmentOptions: [
      {
        type: "real-estate",
        title: "Real Estate",
        description: "Investment in government-approved property starting from",
        startingPrice: "200,000",
        currency: "$",
      },
      {
        type: "contribution",
        title: "EDF Contribution",
        description:
          "Donation to the Economic Diversification Fund (EDF) starting from",
        startingPrice: "200,000",
        currency: "$",
      },
    ],
    visaFreeCountries: [
      { name: "Andorra" },
      { name: "Anguilla" },
      { name: "Antigua and Barbuda" },
      { name: "Argentina" },
      { name: "Armenia", note: "*" },
      { name: "Aruba" },
      { name: "Austria" },
      { name: "Bahamas" },
      { name: "Bangladesh", note: "*" },
      { name: "Barbados" },
      { name: "Belarus" },
      { name: "Belgium" },
      { name: "Belize" },
      { name: "Bermuda" },
      { name: "Bolivia", note: "*" },
      { name: "Bonaire; St. Eustatius and Saba" },
      { name: "Bosnia and Herzegovina" },
      { name: "Botswana" },
      { name: "Brazil" },
      { name: "British Virgin Islands" },
      { name: "Bulgaria" },
      { name: "Burundi", note: "*" },
      { name: "Cambodia", note: "*" },
      { name: "Cape Verde Islands", note: "*" },
      { name: "Cayman Islands" },
      { name: "China" },
      { name: "Colombia" },
      { name: "Comoro Islands", note: "*" },
      { name: "Cook Islands" },
      { name: "Costa Rica" },
      { name: "Croatia" },
      { name: "Cuba" },
      { name: "Curacao" },
      { name: "Cyprus" },
      { name: "Czech Republic" },
      { name: "Denmark" },
      { name: "Dominican Republic" },
      { name: "Ecuador" },
      { name: "Egypt", note: "*" },
      { name: "Estonia" },
      { name: "eSwatini" },
      { name: "Faroe Islands" },
      { name: "Fiji" },
      { name: "Finland" },
      { name: "France" },
      { name: "French Guiana" },
      { name: "French Polynesia" },
      { name: "French West Indies" },
      { name: "Germany" },
      { name: "Gibraltar" },
      { name: "Greece" },
      { name: "Greenland" },
      { name: "Grenada" },
      { name: "Guinea-Bissau", note: "*" },
      { name: "Guyana" },
      { name: "Haiti" },
      { name: "Hong Kong (SAR China)" },
      { name: "Hungary" },
      { name: "Iceland" },
      { name: "Iran", note: "*" },
      { name: "Ireland" },
      { name: "Israel" },
      { name: "Italy" },
      { name: "Jamaica" },
      { name: "Jordan", note: "*" },
      { name: "Kenya" },
      { name: "Kosovo" },
      { name: "Laos", note: "*" },
      { name: "Latvia" },
      { name: "Lesotho" },
      { name: "Liechtenstein" },
      { name: "Lithuania" },
      { name: "Luxembourg" },
      { name: "Macao (SAR China)" },
      { name: "Madagascar", note: "*" },
      { name: "Malawi" },
      { name: "Malaysia" },
      { name: "Maldives", note: "*" },
      { name: "Malta" },
      { name: "Mauritania", note: "*" },
      { name: "Mauritius" },
      { name: "Mayotte" },
      { name: "Micronesia" },
      { name: "Moldova" },
      { name: "Monaco" },
      { name: "Montenegro" },
      { name: "Montserrat" },
      { name: "Mozambique", note: "*" },
      { name: "Nepal", note: "*" },
      { name: "Netherlands" },
      { name: "New Caledonia" },
      { name: "Nicaragua", note: "*" },
      { name: "Niue" },
      { name: "Norway" },
      { name: "Palau Islands", note: "*" },
      { name: "Palestinian Territory" },
      { name: "Panama" },
      { name: "Peru" },
      { name: "Philippines" },
      { name: "Poland" },
      { name: "Portugal" },
      { name: "Reunion" },
      { name: "Romania" },
      { name: "Russian Federation" },
      { name: "Rwanda", note: "*" },
      { name: "Samoa", note: "*" },
      { name: "San Marino" },
      { name: "Senegal", note: "*" },
      { name: "Serbia" },
      { name: "Seychelles", note: "*" },
      { name: "Sierra Leone", note: "*" },
      { name: "Singapore" },
      { name: "Slovakia" },
      { name: "Slovenia" },
      { name: "Solomon Islands", note: "*" },
      { name: "Somalia", note: "*" },
      { name: "South Korea", note: "**" },
      { name: "Spain" },
      { name: "Sri Lanka", note: "**" },
      { name: "St. Helena", note: "*" },
      { name: "St. Kitts and Nevis" },
      { name: "St. Lucia" },
      { name: "St. Maarten" },
      { name: "St. Vincent and the Grenadines" },
      { name: "Suriname" },
      { name: "Sweden" },
      { name: "Switzerland" },
      { name: "Tanzania" },
      { name: "The Gambia" },
      { name: "Timor-Leste", note: "*" },
      { name: "Togo", note: "*" },
      { name: "Tonga", note: "*" },
      { name: "Trinidad and Tobago" },
      { name: "Turks and Caicos Islands" },
      { name: "Tuvalu", note: "*" },
      { name: "Uganda", note: "*" },
      { name: "Ukraine" },
      { name: "Uruguay" },
      { name: "Uzbekistan" },
      { name: "Vanuatu" },
      { name: "Vatican City" },
      { name: "Venezuela" },
      { name: "Zambia" },
    ],
  },

  grenada: {
    slug: "grenada",
    country: "Grenada",
    type: "citizenship",
    tagline: "Benefit from the advantages of the Spice Island of the Caribbean",
    heroImage: "/images/grenada.webp",
    highlights: [
      "Citizenship for life",
      "Cost efficient investment options",
      "Visa-free access to more than 135 countries including UK, Schengen Area, Hong Kong, Singapore, and China",
      "USA E-2 Treaty Country",
      "Approval in 3+ months",
      "Member of the British Commonwealth",
    ],
    description: `Grenada Citizenship by Investment Program enables foreign investors to become citizens of Grenada in exchange for an economic contribution to the country. It has been one of the most cost-efficient and profitable Caribbean CBI programs among high-net-worth individuals to diversify their assets.`,
    benefits: [
      "Visa-free access to more than 135 countries including UK, Schengen Area, Hong Kong, Singapore, and China",
      "Part of the UN, the British Commonwealth, OECS, OAS, and CARICOM",
      "Citizenship is transferable to generations",
      "Fully Remote Procedure",
      "Fast Growing Economy",
      "Stable Democracy",
      "Straightforward process",
      "Ease of global and travel mobility",
      "Ability to live, work and study",
      "High tolerancy and welcoming environment",
      "Dual/Multiple Citizenship",
      "Citizenship for you, your spouse, children under 30 years of age, unmarried siblings, parents and grandparents including spouse's",
      "Favourable Tax Regime",
      "Ideal country for families",
      "Lower living cost",
      "High level of island safety",
      "High quality of life",
      "English as an official language",
      "No language test",
      "No physical residence requirement",
      "No wealth tax",
      "No education requirement",
      "Crypto-Friendly",
      "Vibrant touristic destination",
      "Business Friendly",
    ],
    investmentOptions: [
      {
        type: "contribution",
        title: "NTF Contribution",
        description:
          "Non-refundable contribution to the Grenada's National Transformation Fund (NTF) starting from",
        startingPrice: "235,000",
        currency: "$",
      },
      {
        type: "real-estate",
        title: "Real Estate",
        description:
          "Investment in government-approved property starting from (co-ownership)",
        startingPrice: "270,000",
        currency: "$",
      },
    ],
    visaFreeCountries: [
      { name: "Andorra" },
      { name: "Anguilla" },
      { name: "Antigua and Barbuda" },
      { name: "Argentina" },
      { name: "Armenia", note: "*" },
      { name: "Aruba" },
      { name: "Austria" },
      { name: "Bahamas" },
      { name: "Bangladesh", note: "*" },
      { name: "Barbados" },
      { name: "Belarus" },
      { name: "Belgium" },
      { name: "Belize" },
      { name: "Bermuda" },
      { name: "Bolivia", note: "*" },
      { name: "Bonaire; St. Eustatius and Saba" },
      { name: "Bosnia and Herzegovina" },
      { name: "Botswana" },
      { name: "Brazil" },
      { name: "British Virgin Islands" },
      { name: "Bulgaria" },
      { name: "Burundi", note: "*" },
      { name: "Cambodia", note: "*" },
      { name: "Cape Verde Islands", note: "*" },
      { name: "Cayman Islands" },
      { name: "China" },
      { name: "Colombia" },
      { name: "Comoro Islands", note: "*" },
      { name: "Cook Islands" },
      { name: "Costa Rica" },
      { name: "Croatia" },
      { name: "Cuba" },
      { name: "Curacao" },
      { name: "Cyprus" },
      { name: "Czech Republic" },
      { name: "Denmark" },
      { name: "Dominican Republic" },
      { name: "Ecuador" },
      { name: "Egypt", note: "*" },
      { name: "Estonia" },
      { name: "eSwatini" },
      { name: "Faroe Islands" },
      { name: "Fiji" },
      { name: "Finland" },
      { name: "France" },
      { name: "French Guiana" },
      { name: "French Polynesia" },
      { name: "French West Indies" },
      { name: "Germany" },
      { name: "Gibraltar" },
      { name: "Greece" },
      { name: "Greenland" },
      { name: "Grenada" },
      { name: "Guinea-Bissau", note: "*" },
      { name: "Guyana" },
      { name: "Haiti" },
      { name: "Hong Kong (SAR China)" },
      { name: "Hungary" },
      { name: "Iceland" },
      { name: "Iran", note: "*" },
      { name: "Ireland" },
      { name: "Israel" },
      { name: "Italy" },
      { name: "Jamaica" },
      { name: "Jordan", note: "*" },
      { name: "Kenya" },
      { name: "Kosovo" },
      { name: "Laos", note: "*" },
      { name: "Latvia" },
      { name: "Lesotho" },
      { name: "Liechtenstein" },
      { name: "Lithuania" },
      { name: "Luxembourg" },
      { name: "Macao (SAR China)" },
      { name: "Madagascar", note: "*" },
      { name: "Malawi" },
      { name: "Malaysia" },
      { name: "Maldives", note: "*" },
      { name: "Malta" },
      { name: "Mauritania", note: "*" },
      { name: "Mauritius" },
      { name: "Mayotte" },
      { name: "Micronesia" },
      { name: "Moldova" },
      { name: "Monaco" },
      { name: "Montenegro" },
      { name: "Montserrat" },
      { name: "Mozambique", note: "*" },
      { name: "Nepal", note: "*" },
      { name: "Netherlands" },
      { name: "New Caledonia" },
      { name: "Nicaragua", note: "*" },
      { name: "Niue" },
      { name: "Norway" },
      { name: "Palau Islands", note: "*" },
      { name: "Palestinian Territory" },
      { name: "Panama" },
      { name: "Peru" },
      { name: "Philippines" },
      { name: "Poland" },
      { name: "Portugal" },
      { name: "Reunion" },
      { name: "Romania" },
      { name: "Russian Federation" },
      { name: "Rwanda", note: "*" },
      { name: "Samoa", note: "*" },
      { name: "San Marino" },
      { name: "Senegal", note: "*" },
      { name: "Serbia" },
      { name: "Seychelles", note: "*" },
      { name: "Sierra Leone", note: "*" },
      { name: "Singapore" },
      { name: "Slovakia" },
      { name: "Slovenia" },
      { name: "Solomon Islands", note: "*" },
      { name: "Somalia", note: "*" },
      { name: "South Korea", note: "**" },
      { name: "Spain" },
      { name: "Sri Lanka", note: "**" },
      { name: "St. Helena", note: "*" },
      { name: "St. Kitts and Nevis" },
      { name: "St. Lucia" },
      { name: "St. Maarten" },
      { name: "St. Vincent and the Grenadines" },
      { name: "Suriname" },
      { name: "Sweden" },
      { name: "Switzerland" },
      { name: "Tanzania" },
      { name: "The Gambia" },
      { name: "Timor-Leste", note: "*" },
      { name: "Togo", note: "*" },
      { name: "Tonga", note: "*" },
      { name: "Trinidad and Tobago" },
      { name: "Turks and Caicos Islands" },
      { name: "Tuvalu", note: "*" },
      { name: "Uganda", note: "*" },
      { name: "Ukraine" },
      { name: "Uruguay" },
      { name: "Uzbekistan" },
      { name: "Vanuatu" },
      { name: "Vatican City" },
      { name: "Venezuela" },
      { name: "Zambia" },
    ],
  },

  malta: {
    slug: "malta",
    country: "Malta",
    type: "citizenship",
    tagline:
      "Receive the best education opportunities for your children with the Maltese citizenship",
    heroImage: "/images/malta.webp",
    highlights: [
      "European Citizenship for Life",
      "Crucial business access to advanced economies",
      "Access to Schengen Area and European Union",
      "Visa-free access to more than 185 countries, including USA, Canada, and UK",
      "Approval in 12+ months",
    ],
    description: `Malta Citizenship by Investment Program, also known as Maltese Citizenship by Naturalization for Exceptional Services by Direct Investment, enables foreign investors to become Maltese citizens in exchange for an economic contribution to the country.`,
    benefits: [
      "Visa-free access to more than 180 countries, including USA, Canada, and UK",
      "Become a European citizen",
      "Become a citizen of the British Commonwealth of Nations",
      "Citizenship is transferable to generations",
      "Maltese citizenship for life through naturalization",
      "Ability to live, work and study within the Schengen Zone",
      "Citizenship for you, your spouse, unmarried couples, same-sex couples, children under 29 years of age, parents, and grandparents",
      "Tax discounts for your business",
      "Multicultural and welcoming environment",
      "Business Friendly",
      "Free access to high quality education and healthcare",
      "Dual/Multiple Citizenship",
      "Warm Mediterranean climate",
      "Rich and diverse culture",
      "High quality of life",
      "High level of security",
      "English as an official language",
      "Lower living cost",
      "Stable political system",
      "Ideal country for families",
      "No real estate tax",
      "No wealth tax",
      "Fast Growing Strong Economy",
    ],
    investmentOptions: [
      {
        type: "real-estate",
        title: "Real Estate",
        description:
          "Investing in property starting from €700,000 OR Leasing property for at least €16,000 annually",
        startingPrice: "700,000",
        currency: "€",
      },
      {
        type: "contribution",
        title: "Contribution",
        description:
          "Contribution to the National Economic and Social Development Fund: €600,000 (36 months to citizenship) or €750,000 (12 months to citizenship) for main applicant, plus €50,000 for everyone else",
        startingPrice: "600,000",
        currency: "€",
      },
      {
        type: "other",
        title: "Donation",
        description:
          "Donations to a local registered scientific, sport, cultural, philanthropic, animal welfare, or artistic civil society organization starting from",
        startingPrice: "10,000",
        currency: "€",
      },
    ],
    visaFreeCountries: [
      { name: "Albania" },
      { name: "American Samoa", note: "**" },
      { name: "Andorra" },
      { name: "Anguilla" },
      { name: "Antigua and Barbuda" },
      { name: "Argentina" },
      { name: "Armenia" },
      { name: "Aruba" },
      { name: "Australia", note: "**" },
      { name: "Austria" },
      { name: "Bahamas" },
      { name: "Bahrain", note: "*" },
      { name: "Bangladesh", note: "*" },
      { name: "Barbados" },
      { name: "Belarus" },
      { name: "Belgium" },
      { name: "Belize" },
      { name: "Bermuda" },
      { name: "Bolivia", note: "*" },
      { name: "Bonaire; St. Eustatius and Saba" },
      { name: "Bosnia and Herzegovina" },
      { name: "Botswana" },
      { name: "Brazil" },
      { name: "British Virgin Islands" },
      { name: "Brunei" },
      { name: "Bulgaria" },
      { name: "Burkina Faso", note: "*" },
      { name: "Burundi", note: "*" },
      { name: "Cambodia", note: "*" },
      { name: "Canada", note: "**" },
      { name: "Cape Verde Islands" },
      { name: "Cayman Islands" },
      { name: "Chile" },
      { name: "Colombia" },
      { name: "Comoro Islands", note: "*" },
      { name: "Cook Islands" },
      { name: "Costa Rica" },
      { name: "Croatia" },
      { name: "Curacao" },
      { name: "Cyprus" },
      { name: "Czech Republic" },
      { name: "Denmark" },
      { name: "Dominica" },
      { name: "Dominican Republic" },
      { name: "Ecuador" },
      { name: "Egypt", note: "*" },
      { name: "El Salvador" },
      { name: "Estonia" },
      { name: "eSwatini" },
      { name: "Falkland Islands" },
      { name: "Faroe Islands" },
      { name: "Fiji" },
      { name: "Finland" },
      { name: "France" },
      { name: "French Guiana" },
      { name: "French Polynesia" },
      { name: "French West Indies" },
      { name: "Gabon", note: "*" },
      { name: "Georgia" },
      { name: "Germany" },
      { name: "Gibraltar" },
      { name: "Greece" },
      { name: "Greenland" },
      { name: "Grenada" },
      { name: "Guam", note: "**" },
      { name: "Guatemala" },
      { name: "Guinea-Bissau", note: "*" },
      { name: "Haiti" },
      { name: "Honduras" },
      { name: "Hong Kong (SAR China)" },
      { name: "Hungary" },
      { name: "Iceland" },
      { name: "Indonesia", note: "*" },
      { name: "Iran", note: "*" },
      { name: "Iraq" },
      { name: "Ireland" },
      { name: "Israel" },
      { name: "Italy" },
      { name: "Jamaica" },
      { name: "Japan" },
      { name: "Jordan", note: "*" },
      { name: "Kazakhstan" },
      { name: "Kiribati" },
      { name: "Kosovo" },
      { name: "Kuwait", note: "*" },
      { name: "Kyrgyzstan" },
      { name: "Laos", note: "*" },
      { name: "Latvia" },
      { name: "Lebanon", note: "*" },
      { name: "Lesotho" },
      { name: "Liechtenstein" },
      { name: "Lithuania" },
      { name: "Luxembourg" },
      { name: "Macao (SAR China)" },
      { name: "Madagascar", note: "*" },
      { name: "Malawi", note: "*" },
      { name: "Malaysia" },
      { name: "Maldives", note: "*" },
      { name: "Marshall Islands" },
      { name: "Mauritania", note: "*" },
      { name: "Mauritius" },
      { name: "Mayotte" },
      { name: "Mexico" },
      { name: "Micronesia" },
      { name: "Moldova" },
      { name: "Monaco" },
      { name: "Mongolia", note: "*" },
      { name: "Montenegro" },
      { name: "Montserrat" },
      { name: "Morocco" },
      { name: "Mozambique", note: "*" },
      { name: "Nepal", note: "*" },
      { name: "Netherlands" },
      { name: "New Caledonia" },
      { name: "New Zealand", note: "**" },
      { name: "Nicaragua" },
      { name: "Niue" },
      { name: "North Macedonia" },
      { name: "Northern Mariana Islands", note: "**" },
      { name: "Norway" },
      { name: "Oman" },
      { name: "Pakistan", note: "**" },
      { name: "Palau Islands" },
      { name: "Palestinian Territory" },
      { name: "Panama" },
      { name: "Papua New Guinea", note: "*" },
      { name: "Paraguay" },
      { name: "Peru" },
      { name: "Philippines" },
      { name: "Poland" },
      { name: "Portugal" },
      { name: "Puerto Rico", note: "**" },
      { name: "Qatar" },
      { name: "Reunion" },
      { name: "Romania" },
      { name: "Rwanda", note: "*" },
      { name: "Samoa" },
      { name: "San Marino" },
      { name: "Sao Tome and Principe" },
      { name: "Saudi Arabia", note: "*" },
      { name: "Senegal" },
      { name: "Serbia" },
      { name: "Seychelles", note: "*" },
      { name: "Sierra Leone", note: "*" },
      { name: "Singapore" },
      { name: "Slovakia" },
      { name: "Slovenia" },
      { name: "Solomon Islands" },
      { name: "Somalia", note: "*" },
      { name: "South Africa" },
      { name: "South Korea", note: "**" },
      { name: "Spain" },
      { name: "Sri Lanka", note: "**" },
      { name: "St. Helena", note: "*" },
      { name: "St. Kitts and Nevis" },
      { name: "St. Lucia" },
      { name: "St. Maarten" },
      { name: "St. Vincent and the Grenadines" },
      { name: "Sweden" },
      { name: "Switzerland" },
      { name: "Taiwan (Chinese Taipei)" },
      { name: "Tajikistan", note: "*" },
      { name: "Tanzania" },
      { name: "Thailand", note: "*" },
      { name: "The Gambia" },
      { name: "Timor-Leste" },
      { name: "Togo", note: "*" },
      { name: "Tonga" },
      { name: "Trinidad and Tobago" },
      { name: "Tunisia" },
      { name: "Türkiye" },
      { name: "Turks and Caicos Islands" },
      { name: "Tuvalu" },
      { name: "Uganda" },
      { name: "Ukraine" },
      { name: "United Arab Emirates" },
      { name: "United Kingdom" },
      { name: "United States", note: "**" },
      { name: "Uruguay" },
      { name: "US Virgin Islands", note: "**" },
      { name: "Uzbekistan" },
      { name: "Vanuatu" },
      { name: "Vatican City" },
      { name: "Venezuela" },
      { name: "Zambia" },
      { name: "Zimbabwe" },
    ],
  },

  portugal: {
    slug: "portugal",
    country: "Portugal",
    type: "residency",
    tagline: "Achieve your dream life in Europe through Portugal Golden Visa",
    heroImage: "/images/portugal.webp",
    highlights: [
      "Physical presence 7 days a year",
      "Minimum € 250,000 Contribution",
      "Approval in 12+ months",
      "Most viable pathway to Portuguese citizenship",
      "Visa-Free Access to the EU and Schengen Zone",
    ],
    description: `Portugal Golden Visa has been one of the most popular residency programs among high-net-worth individuals worldwide. Foreign investors can receive a residence permit through the Portuguese Golden Visa Program in exchange for financial contributions in Portugal.`,
    benefits: [
      "Eligibility for Portuguese citizenship after residing in Portugal for 5 years",
      "Visa-free access to Schengen area and the rest of EU",
      "A whole range of investment options",
      "Strong and Stable Democracy",
      "Growing EU Economy",
      "Part of EU, NATO, OECD",
      "Ability to live, work, and study",
      "Permanent residency for you, your spouse or partner, financially dependent children under 26, dependent parents and underage siblings under custody",
      "Free access to quality education and healthcare",
      "Dual/Multiple Citizenship",
      "High quality of life",
      "High level of security",
      "Warm Mediterranean climate",
      "Rich and diverse culture",
      "Access to advanced economies",
      "Low living cost",
      "No tax on worldwide income",
      "High return on investment",
      "Ideal country for families",
      "No interview",
      "No language test",
      "Crypto-Friendly",
    ],
    investmentOptions: [
      {
        type: "other",
        title: "Fund Investment",
        description:
          "Investment in a qualified Portuguese investment fund starting from",
        startingPrice: "500,000",
        currency: "€",
      },
      {
        type: "contribution",
        title: "Cultural Contribution",
        description:
          "Support of artistic production or recovery/maintenance of national cultural heritage (€200,000 in low population density areas)",
        startingPrice: "250,000",
        currency: "€",
      },
      {
        type: "other",
        title: "Capital Investment",
        description:
          "Creation of minimum 10 new jobs (8 in low density areas) OR €500,000 for incorporation of a commercial company creating minimum 5 permanent jobs",
        startingPrice: "500,000",
        currency: "€",
      },
    ],
    visaFreeCountries: [],
  },

  "uk-start-up-visa": {
    slug: "uk-start-up-visa",
    country: "UK Start Up Visa",
    type: "residency",
    tagline:
      "Establish your business in the heart of the financial business location",
    heroImage: "/images/uk-start-up-visa.webp",
    highlights: [
      "Viable pathway to British citizenship",
      "Financial Business Centre",
      "Fast and cost-effective immigration path to the United Kingdom",
      "No minimum investment",
      "Approval in 3-8 weeks",
    ],
    description: `United Kingdom Start-Up Visa is for entrepreneurs who want to start or invest in a new United Kingdom-based company for the first time. You can easily build and expand your innovative, fresh, and viable business idea in the most business-friendly environment possible.`,
    benefits: [
      "Possibility to become a UK citizen after 6 years of residency",
      "Travel mobility with one of the most powerful visas",
      "Strong and Stable Democracy",
      "Part of the UN, OECD, G8, and NATO",
      "High Economic Growth",
      "Ability to live, work and study anywhere in the UK",
      "2 years of residency for you, your spouse, and children dependent children",
      "Convertible to the UK Innovator Visa",
      "Access to high quality education and world class healthcare",
      "Dual/Multiple Citizenship",
      "High quality of life",
      "High level of security",
      "Enhanced business access to advanced economies",
      "Tax discounts for your business",
      "Multicultural and welcoming environment",
      "High level of religious and ethnic tolerance",
      "Business Friendly",
      "Live 2 years to develop your business",
      "English as an official language",
      "Work in any job you want besides your business",
    ],
    investmentOptions: [
      {
        type: "other",
        title: "Requirements",
        description:
          "Minimum £1,270 proof of funds in UK bank account, endorsement from UK higher education authority or business organization, English proficiency certificate at level B2, no previously established business in UK, clean criminal record. Business must be innovative, unique, and viable.",
        startingPrice: "1,270",
        currency: "£",
      },
    ],
    visaFreeCountries: [],
  },

  "uk-innovator-founder-visa": {
    slug: "uk-innovator-founder-visa",
    country: "UK Innovator Founder Visa",
    type: "residency",
    tagline:
      "Shape the future in the UK with an innovative idea and a global vision",
    heroImage: "/images/uk-innovator-founder-visa.webp",
    highlights: [
      "Financial Business Centre",
      "Viable pathway to British citizenship",
      "Fast and cost-effective immigration path to the United Kingdom",
      "Minimum £50,000 Investment",
      "Approval in 1-8 weeks",
    ],
    description: `United Kingdom Innovator Founder Visa is for experienced business people who want to set up or invest in a new United Kingdom-based company. You can benefit from excellent business links between Europe and America in the United Kingdom.`,
    benefits: [
      "Part of the UN, OECD, G8, and NATO",
      "Eligibility for British citizenship after 5 years of residency",
      "Permanent Residency for you, your spouse/civil partner and children under 18",
      "Straightforward process",
      "Ease of global and travel mobility",
      "Ability to live, work and study",
      "High tolerancy and welcoming environment",
      "Ideal country for families",
      "High quality of life",
      "World-renowned schools",
      "High level of security",
      "Enhanced business access to advanced economies",
      "Tax discounts for your business",
      "Live 3 years to develop your business",
      "English as an official language",
      "Panel of pre-approved innovative projects available",
      "Dual/Multiple Citizenship",
    ],
    investmentOptions: [
      {
        type: "other",
        title: "Investment Requirement",
        description:
          "Minimum £50,000 to invest in your new business, plus £1,270 proof of funds in UK bank account, endorsement letter from Home Office approved endorsing body, English proficiency certificate at level B2, scalable/innovative/viable business project, clean criminal record.",
        startingPrice: "50,000",
        currency: "£",
      },
    ],
    visaFreeCountries: [],
  },

  hungary: {
    slug: "hungary",
    country: "Hungary",
    type: "residency",
    tagline:
      "More than investment, it is a marvelous family lifestyle you deserve in the booming heart of Central Europe",
    heroImage: "/images/hungary.webp",
    highlights: [
      "Lowest corporate income tax in Europe by 9%",
      "Minimum € 250.000 Property Fund Investment",
      "Access granted to Schengen Area and European Union",
      "Investment is made after the Residency Cards are ready",
      "Approval in 2+ months",
    ],
    description: `Hungary's Guest Investor Program (GIP), relaunched in 2024, offers one of the fastest and most affordable routes to EU residency with no mandatory stay requirements. For a minimum investment of €250,000 in approved real estate funds, investors and their families gain renewable European residency.`,
    benefits: [
      "Visa-free access to more than 170 countries",
      "Most affordable permanent residency program in Europe",
      "Indefinitely renewable 10 year residency as long as the investment is maintained",
      "Eligibility for Hungarian citizenship after residing in Hungary for 8 years",
      "Fast Growing Strong Economy",
      "Ability to live, work and study",
      "Permanent Residency for you, your spouse, and children under 18 years of age",
      "Get pre-approved (D visa), then invest within 90 days. Residency guaranteed in 30 days after funding",
      "High return on investment",
      "Dynamic touristic destination",
      "Enhanced business access to advanced economies",
      "Low government and renewal fees",
      "Tax discounts for your business",
      "Multicultural and welcoming environment",
      "Business Friendly",
      "Free access to high quality education and healthcare",
      "Rich and ancient cultural and historical heritage",
      "High quality of life",
      "High level of security",
      "Ideal country for families",
      "Low living and business costs",
      "No interview",
      "No language test",
      "No physical residence requirement",
      "No education requirement",
    ],
    investmentOptions: [
      {
        type: "real-estate",
        title: "Real Estate Fund",
        description: "Investment in property fund starting from",
        startingPrice: "250,000",
        currency: "€",
      },
      {
        type: "contribution",
        title: "Contribution",
        description:
          "Contributing into a Hungarian college or university supported by a public charity foundation starting from",
        startingPrice: "1,000,000",
        currency: "€",
      },
    ],
    visaFreeCountries: [],
  },

  greece: {
    slug: "greece",
    country: "Greece",
    type: "residency",
    tagline: "Marvelous destination to live with your family beyond investment",
    heroImage: "/images/greece.webp",
    highlights: [
      "Crucial business location at the crossroads of Africa, Asia, and Europe",
      "Minimum € 250,000 Investment",
      "Access to Schengen Area and European Union",
      "Most viable pathway to Greek citizenship",
      "Approval in 6+ months",
    ],
    description: `Greece Golden Visa enables foreign investors to receive a permanent residency permit in exchange for a minimum capital investment of € 250,000. It has been known as one of the most popular and affordable golden visa programs providing European access.`,
    benefits: [
      "Visa-free access to more than 180 countries",
      "Possibility of becoming a European citizen",
      "Possibility of Greek citizenship for life after residing in Greece for 7 years",
      "Renewable residency permit every 5 years",
      "Fast Growing Strong Economy",
      "Ability to live, and study",
      "Permanent Residency for you, your spouse, children under 21 years of age, and parents including your spouse's",
      "High return on investment",
      "Dynamic touristic destination",
      "Enhanced business access to advanced economies",
      "Low government and renewal fees",
      "Tax discounts for your business",
      "Multicultural and welcoming environment",
      "Business Friendly",
      "Growing technology industry",
      "Free access to high quality education and healthcare options",
      "Warm Mediterranean climate",
      "Rich and ancient cultural and historical heritage",
      "High quality of life",
      "High level of security",
      "Ideal country for families",
      "No interview",
      "No language test",
      "No physical residence requirement",
      "No education requirement",
    ],
    investmentOptions: [
      {
        type: "real-estate",
        title: "Real Estate (Conversion/Restoration)",
        description:
          "Conversion of commercial properties into residential use or restoration of listed buildings regardless of location or size",
        startingPrice: "250,000",
        currency: "€",
      },
      {
        type: "real-estate",
        title: "Real Estate (Rural Areas)",
        description:
          "Purchase of a single property of at least 120 square meters in rural areas or less densely populated cities and islands",
        startingPrice: "400,000",
        currency: "€",
      },
      {
        type: "real-estate",
        title: "Real Estate (Major Cities)",
        description:
          "Purchase of properties in Athens, Thessaloniki, and islands with more than 3,100 people",
        startingPrice: "800,000",
        currency: "€",
      },
      {
        type: "other",
        title: "Bank Deposit",
        description:
          "Investing in a Greek bank for at least 1 year with automatic renewal starting from",
        startingPrice: "500,000",
        currency: "€",
      },
    ],
    visaFreeCountries: [],
  },

  uae: {
    slug: "uae",
    country: "UAE",
    type: "residency",
    tagline:
      "Expand your wealth in the financial and touristic hub of the Middle East",
    heroImage: "/images/uae.webp",
    highlights: [
      "Crucial business location at the crossroads of the Middle East, Asia, and Europe",
      "Favorable tax regime for investors",
      "10 Year Golden Visa",
      "High return on real estate investment",
      "Approval in 2-8 weeks",
    ],
    description: `UAE Golden Visa, also known as Dubai Golden Visa, enables foreign investors to receive a residency permit in exchange for an economic contribution to the country. It is the most popular and profitable golden visa program in the Arabian Gulf.`,
    benefits: [
      "Part of the UN, the Arab League, and the Gulf Cooperation Council",
      "Renewable residency permit every 10 years",
      "Fast Growing Strong Economy",
      "Ability to live, work and study in seven emirates of the UAE",
      "Right to work for all family members",
      "Permanent Residency for you, your spouse, and your dependent children under 30",
      "Favorable tax regime for investors",
      "Enhanced business access to advanced economies",
      "Low government and renewal fees",
      "Tax discounts for your business",
      "Multicultural and welcoming environment",
      "Business Friendly",
      "Modern lifestyle",
      "Access to high quality education and healthcare options",
      "High quality of life",
      "High level of security",
    ],
    investmentOptions: [
      {
        type: "real-estate",
        title: "Real Estate",
        description: "Investment in property starting from",
        startingPrice: "2,000,000",
        currency: "AED",
      },
      {
        type: "other",
        title: "Bank Deposit",
        description:
          "Depositing into local banks for 2 years with the 4% yield starting from",
        startingPrice: "2,000,000",
        currency: "AED",
      },
    ],
    visaFreeCountries: [],
  },

  australia: {
    slug: "australia",
    country: "Australia",
    type: "residency",
    tagline: "The top destination for global talent and innovation",
    heroImage: "/images/australia.webp",
    highlights: [
      "No Investment Required",
      "Fast-Track to Permanent Residency",
      "Family Inclusion",
      "World-Class Quality of Life",
      "Flexible Requirements",
    ],
    description: `The National Innovation Visa (NIV) offers a streamlined permanent residency pathway for exceptional global talent. By welcoming and attracting individuals with extraordinary skills and leadership, the NIV strengthens Australia's economy through innovation, knowledge transfer, and job creation.`,
    benefits: [
      "No minimum investment required",
      "Fast-track processing",
      "High quality of life",
      "Top-tier education access",
      "A stable and secure environment",
      "No strict age limit",
      "Flexible English requirements",
      "Permanent residency for you, your partner (including civil/de facto) and dependent children under 23",
      "Mandatory employer retirement contributions",
      "Simplified citizenship pathway",
      "Warm climate",
      "Multicultural and welcoming environment",
      "English as the official language",
    ],
    investmentOptions: [
      {
        type: "other",
        title: "National Innovation Visa",
        description:
          "Requirements: Be highly accomplished and internationally recognized in your field with proof like senior roles, patents, awards, or published work. Show you'll benefit Australia's economy, society, culture, academics, arts, or sports. Have a nomination from an approved Australian organization, expert, or government agency.",
        startingPrice: "0",
        currency: "$",
      },
    ],
    visaFreeCountries: [],
  },
};

// Helper function to get all program slugs for static generation
export function getAllProgramSlugs(): string[] {
  return Object.keys(programsData);
}
