export const residencyPrograms = [
  // Citizenship Programs
  {
    location: "Saint Kitts and Nevis",
    type: "Citizenship by investment program",
    price: "Starting from $ 250,000",
    image: "/images/pexels-8pcarlos-morocho-2150734957-35260825.webp",
    slug: "st-kitts-nevis",
  },
  {
    location: "Saint Lucia",
    type: "Citizenship by investment program",
    price: "Starting from $ 100,000",
    image: "/images/global-residency/244205-St-Lucia.jpg",
    slug: "st-lucia",
  },
  {
    location: "Turkey",
    type: "Citizenship by investment program",
    price: "Starting from $ 400,000",
    image: "/images/global-residency/Turkey-small.jpg",
    slug: "turkey",
  },
  {
    location: "Vanuatu",
    type: "Citizenship by investment program",
    price: "Starting from $ 130,000",
    image: "/images/global-residency/Vanatu-small.jpg",
    slug: "vanuatu",
  },
  {
    location: "Antigua & Barbuda",
    type: "Citizenship by investment program",
    price: "Starting from $ 100,000",
    image: "/images/pexels-geoffrey-currie-2153251493-33128243.webp",
    slug: "antigua-barbuda",
  },
  {
    location: "Dominica",
    type: "Citizenship by investment program",
    price: "Starting from $ 100,000",
    image: "/images/global-residency/dominica-.png.webp",
    slug: "dominica",
  },
  {
    location: "Grenada",
    type: "Citizenship by investment program",
    price: "Starting from $ 235,000",
    image: "/images/global-residency/Grenada-small.jpg",
    slug: "grenada",
  },
  {
    location: "Malta (Citizenship)",
    type: "Citizenship by investment program",
    price: "Starting from € 600,000",
    image: "/images/global-residency/malta.jpg",
    slug: "malta-citizenship",
  },

  // Residency Programs
  {
    location: "Portugal",
    type: "Residency by investment program",
    price: "Starting from € 500,000",
    image: "/images/global-residency/Portugal-small.jpg",
    slug: "portugal",
  },
  {
    location: "United Kingdom",
    type: "Residency by investment program",
    price: "Starting from £ 2,000,000",
    image: "/images/global-residency/london-blog-1.jpg",
    slug: "united-kingdom",
  },
  {
    location: "Greece",
    type: "Residency by investment program",
    price: "Starting from € 250,000",
    image: "/images/global-residency/Greece-small.jpg",
    slug: "greece",
  },
  {
    location: "Hungary",
    type: "Residency by investment program",
    price: "Starting from € 250,000",
    image: "/images/pexels-mahmudul-hasan-2004633-35257841.webp",
    slug: "hungary",
  },
  {
    location: "Latvia",
    type: "Residency by investment program",
    price: "Starting from € 50,000",
    image: "/images/pexels-rada-aslanova-150604297-34567860.webp",
    slug: "latvia",
  },
  {
    location: "Malta (Residency)",
    type: "Residency by investment program",
    price: "Starting from € 135,000",
    image: "/images/global-residency/malta.jpg",
    slug: "malta-residency",
  },
];
