export const residencyPrograms = [
  // Citizenship Programs
  {
    location: "Saint Kitts and Nevis",
    type: "Citizenship by investment program",
    price: "Starting from $ 250,000",
    image: "/images/pexels-8pcarlos-morocho-2150734957-35260825.webp",
    slug: "st-kitts-nevis",
  },
  {
    location: "Saint Lucia",
    type: "Citizenship by investment program",
    price: "Starting from $ 240,000",
    image: "/images/global-residency/244205-St-Lucia.jpg",
    slug: "st-lucia",
  },
  {
    location: "Turkey",
    type: "Citizenship by investment program",
    price: "Starting from $ 400,000",
    image: "/images/global-residency/Turkey-small.jpg",
    slug: "turkey",
  },
  {
    location: "Vanuatu",
    type: "Citizenship by investment program",
    price: "Starting from $ 140,400",
    image: "/images/global-residency/Vanatu-small.jpg",
    slug: "vanuatu",
  },
  {
    location: "Antigua & Barbuda",
    type: "Citizenship by investment program",
    price: "Starting from $ 230,000",
    image: "/images/pexels-geoffrey-currie-2153251493-33128243.webp",
    slug: "antigua-barbuda",
  },
  {
    location: "Dominica",
    type: "Citizenship by investment program",
    price: "Starting from $ 200,000",
    image: "/images/global-residency/dominica-.png.webp",
    slug: "dominica",
  },
  {
    location: "Grenada",
    type: "Citizenship by investment program",
    price: "Starting from $ 235,000",
    image: "/images/global-residency/Grenada-small.jpg",
    slug: "grenada",
  },
  {
    location: "Malta",
    type: "Citizenship by investment program",
    price: "Starting from € 600,000",
    image: "/images/global-residency/malta.jpg",
    slug: "malta",
  },

  // Residency Programs
  {
    location: "Portugal",
    type: "Residency by investment program",
    price: "Starting from € 250,000",
    image: "/images/global-residency/Portugal-small.jpg",
    slug: "portugal",
  },
  {
    location: "UK Start Up Visa",
    type: "Residency by investment program",
    price: "No minimum investment",
    image: "/images/global-residency/london-blog-1.jpg",
    slug: "uk-start-up-visa",
  },
  {
    location: "UK Innovator Founder Visa",
    type: "Residency by investment program",
    price: "Starting from £ 50,000",
    image: "/images/global-residency/london-blog-1.jpg",
    slug: "uk-innovator-founder-visa",
  },
  {
    location: "Greece",
    type: "Residency by investment program",
    price: "Starting from € 250,000",
    image: "/images/global-residency/Greece-small.jpg",
    slug: "greece",
  },
  {
    location: "Hungary",
    type: "Residency by investment program",
    price: "Starting from € 250,000",
    image: "/images/pexels-mahmudul-hasan-2004633-35257841.webp",
    slug: "hungary",
  },
  {
    location: "UAE",
    type: "Residency by investment program",
    price: "Starting from AED 2,000,000",
    image: "/images/global-residency/uae.jpg",
    slug: "uae",
  },
  {
    location: "Australia",
    type: "Residency by investment program",
    price: "No minimum investment",
    image: "/images/global-residency/australia.jpg",
    slug: "australia",
  },
];
